import { z } from "zod";

export const TempOrg1Validator = z.object({
    id: z.string().uuid().optional(), // UUID generated by Sequelize; optional for creation
    orgName: z.string().max(255, "Organization name must be at most 255 characters."),
    address: z.string().max(255, "Address must be at most 255 characters."),
    city: z.string().max(255, "City must be at most 255 characters."),
    country: z.string().max(255, "Country must be at most 255 characters."),
    tin: z.string().max(255, "TIN must be at most 255 characters.").optional(), // Optional and unique
    industry: z.string().max(255, "Industry must be at most 255 characters.").optional(),
    establishYear: z.number().int().min(1800).max(new Date().getFullYear()).optional(), // Ensure realistic year
    stakeholderCount: z.number().int().min(0).optional(), // Default is 1; cannot be negative
    emergencyContactCount: z.number().int().min(0).optional(), // Default is 0; cannot be negative
    status: z.enum(["pending", "verified", "rejected"]).optional(), // Default is 'pending'
    tempUserId: z.string().uuid().optional(), // Reference to TempUser
}).strict();


